### ISSUE TITLE
sql error messages

### ISSUE THREAD

**Issue by aristosv** [Ulisses1478/Shinobi-Docker#2]
Hi,

I keep getting these messages in the logs
```
0|camera  |     at addChunk (_stream_readable.js:263:12),
0|camera  |     at readableAddChunk (_stream_readable.js:250:11),
0|camera  |     at Socket.Readable.push (_stream_readable.js:208:10),
0|camera  |     at TCP.onread (net.js:607:20),
0|camera  |     --------------------,
0|camera  |     at Protocol._enqueue (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:144:48),
0|camera  |     at Protocol.handshake (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:51:23),
0|camera  |     at Connection.connect (/shinobi/node_modules/mysql/lib/Connection.js:119:18),
0|camera  |     at _bluebird.default (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:82:18),
0|camera  |     at Promise._execute (/shinobi/node_modules/bluebird/js/release/debuggability.js:313:9),
0|camera  |     at Promise._resolveFromExecutor (/shinobi/node_modules/bluebird/js/release/promise.js:483:18),
0|camera  |     at new Promise (/shinobi/node_modules/bluebird/js/release/promise.js:79:10),
0|camera  |     at Client_MySQL.acquireRawConnection (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:77:12),
0|camera  |     at create (/shinobi/node_modules/knex/lib/client.js:282:21),
0|camera  |     at utils_1.tryPromise (/shinobi/node_modules/tarn/lib/Pool.js:315:34),
0|camera  |     at Object.tryPromise (/shinobi/node_modules/tarn/lib/utils.js:53:24),
0|camera  |     at Promise (/shinobi/node_modules/tarn/lib/Pool.js:315:17),
0|camera  |     at new Promise (<anonymous>),
0|camera  |     at callbackOrPromise (/shinobi/node_modules/tarn/lib/Pool.js:306:12),
0|camera  |     at Pool._create (/shinobi/node_modules/tarn/lib/Pool.js:236:9),
0|camera  |     at Pool._doCreate (/shinobi/node_modules/tarn/lib/Pool.js:208:36),
0|camera  |   code: 'ER_BAD_DB_ERROR',,
camera  |   errno: 1049,,
0|camera  |   sqlMessage: 'Unknown database \'ccio\'',,
0|camera  |   sqlState: '42000',,
0|camera  |   fatal: true },
0|camera  | { Error: ER_BAD_DB_ERROR: Unknown database 'ccio',
0|camera  |     at Handshake.Sequence._packetToError (/shinobi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14),
0|camera  |     at Handshake.ErrorPacket (/shinobi/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18),
0|camera  |     at Protocol._parsePacket (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:291:23),
0|camera  |     at Parser._parsePacket (/shinobi/node_modules/mysql/lib/protocol/Parser.js:433:10),
0|camera  |     at Parser.write (/shinobi/node_modules/mysql/lib/protocol/Parser.js:43:10),
0|camera  |     at Protocol.write (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:38:16),
0|camera  |     at Socket.<anonymous> (/shinobi/node_modules/mysql/lib/Connection.js:91:28),
0|camera  |     at Socket.<anonymous> (/shinobi/node_modules/mysql/lib/Connection.js:525:10),
0|camera  |     at emitOne (events.js:116:13),
0|camera  |     at Socket.emit (events.js:211:7),
0|camera  |     at addChunk (_stream_readable.js:263:12),
0|camera  |     at readableAddChunk (_stream_readable.js:250:11),
0|camera  |     at Socket.Readable.push (_stream_readable.js:208:10),
0|camera  |     at TCP.onread (net.js:607:20),
0|camera  |     --------------------,
0|camera  |     at Protocol._enqueue (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:144:48),
0|camera  |     at Protocol.handshake (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:51:23),
0|camera  |     at Connection.connect (/shinobi/node_modules/mysql/lib/Connection.js:119:18),
0|camera  |     at _bluebird.default (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:82:18),
0|camera  |     at Promise._execute (/shinobi/node_modules/bluebird/js/release/debuggability.js:313:9),
0|camera  |     at Promise._resolveFromExecutor (/shinobi/node_modules/bluebird/js/release/promise.js:483:18),
0|camera  |     at new Promise (/shinobi/node_modules/bluebird/js/release/promise.js:79:10),
0|camera  |     at Client_MySQL.acquireRawConnection (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:77:12),
0|camera  |     at create (/shinobi/node_modules/knex/lib/client.js:282:21),
0|camera  |     at utils_1.tryPromise (/shinobi/node_modules/tarn/lib/Pool.js:315:34),
0|camera  |     at Object.tryPromise (/shinobi/node_modules/tarn/lib/utils.js:53:24),
0|camera  |     at Promise (/shinobi/node_modules/tarn/lib/Pool.js:315:17),
0|camera  |     at new Promise (<anonymous>),
0|camera  |     at callbackOrPromise (/shinobi/node_modules/tarn/lib/Pool.js:306:12),
0|camera  |     at Pool._create (/shinobi/node_modules/tarn/lib/Pool.js:236:9),
0|camera  |     at Pool._doCreate (/shinobi/node_modules/tarn/lib/Pool.js:208:36),
0|camera  |   code: 'ER_BAD_DB_ERROR',,
camera  |   errno: 1049,,
0|camera  |   sqlMessage: 'Unknown database \'ccio\'',,
0|camera  |   sqlState: '42000',,
0|camera  |   fatal: true },
0|camera  | { Error: ER_BAD_DB_ERROR: Unknown database 'ccio',
0|camera  |     at Handshake.Sequence._packetToError (/shinobi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14),
0|camera  |     at Handshake.ErrorPacket (/shinobi/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18),
0|camera  |     at Protocol._parsePacket (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:291:23),
0|camera  |     at Parser._parsePacket (/shinobi/node_modules/mysql/lib/protocol/Parser.js:433:10),
0|camera  |     at Parser.write (/shinobi/node_modules/mysql/lib/protocol/Parser.js:43:10),
0|camera  |     at Protocol.write (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:38:16),
0|camera  |     at Socket.<anonymous> (/shinobi/node_modules/mysql/lib/Connection.js:91:28),
0|camera  |     at Socket.<anonymous> (/shinobi/node_modules/mysql/lib/Connection.js:525:10),
0|camera  |     at emitOne (events.js:116:13),
0|camera  |     at Socket.emit (events.js:211:7),
0|camera  |     at addChunk (_stream_readable.js:263:12),
0|camera  |     at readableAddChunk (_stream_readable.js:250:11),
0|camera  |     at Socket.Readable.push (_stream_readable.js:208:10),
0|camera  |     at TCP.onread (net.js:607:20),
0|camera  |     --------------------,
0|camera  |     at Protocol._enqueue (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:144:48),
0|camera  |     at Protocol.handshake (/shinobi/node_modules/mysql/lib/protocol/Protocol.js:51:23),
0|camera  |     at Connection.connect (/shinobi/node_modules/mysql/lib/Connection.js:119:18),
0|camera  |     at _bluebird.default (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:82:18),
0|camera  |     at Promise._execute (/shinobi/node_modules/bluebird/js/release/debuggability.js:313:9),
0|camera  |     at Promise._resolveFromExecutor (/shinobi/node_modules/bluebird/js/release/promise.js:483:18),
0|camera  |     at new Promise (/shinobi/node_modules/bluebird/js/release/promise.js:79:10),
0|camera  |     at Client_MySQL.acquireRawConnection (/shinobi/node_modules/knex/lib/dialects/mysql/index.js:77:12),
0|camera  |     at create (/shinobi/node_modules/knex/lib/client.js:282:21),
0|camera  |     at utils_1.tryPromise (/shinobi/node_modules/tarn/lib/Pool.js:315:34),
0|camera  |     at Object.tryPromise (/shinobi/node_modules/tarn/lib/utils.js:53:24),
0|camera  |     at Promise (/shinobi/node_modules/tarn/lib/Pool.js:315:17),
0|camera  |     at new Promise (<anonymous>),
0|camera  |     at callbackOrPromise (/shinobi/node_modules/tarn/lib/Pool.js:306:12),
0|camera  |     at Pool._create (/shinobi/node_modules/tarn/lib/Pool.js:236:9),
0|camera  |     at Pool._doCreate (/shinobi/node_modules/tarn/lib/Pool.js:208:36),
0|camera  |   code: 'ER_BAD_DB_ERROR',,
camera  |   errno: 1049,,
0|camera  |   sqlMessage: 'Unknown database \'ccio\'',,
0|camera  |   sqlState: '42000',,
0|camera  |   fatal: true },
```

This is how I installed it.

`docker run -d --restart always --name shinobi -h shinobi -p 8080:8080/tcp -v shinobi:/shinobi:rw -v shinobi:/var/lib/mysql:rw -v shinobi:/shinobi/videos:rw ulisses1478/shinobi`

**Comment by Ulisses1478** [comment]
This is not a problem if your shinobi works right its just the database is not connecting right, because is running without any credentials. I tried to fix but something with this particular mysql installation i did cant run with credentials when i get more issues i will remake the docker and will not get this errors anymore.
If there is a problem with the shinobi, tell me i will test and fix

**Comment by nate922** [comment]
Hi Guys,

I'm also receiving these messages:
0|camera | code: 'ER_BAD_DB_ERROR',
0|camera | errno: 1049,
0|camera | sqlMessage: 'Unknown database \'ccio\'',
0|camera | sqlState: '42000',
0|camera | fatal: true }

I can't add a user after logging into /super
When I hit save, nothing happens

I also can't change the admin@shinobi.video password, could this be SQL related?

Thanks.

**Comment by Ulisses1478** [comment]
Hey nate, Probably your database is not installed properly.
Try passing the environment arguments.
DB_USER=root
DB_PASS=root
DB_NAME=shinobi

**Comment by Ulisses1478** [comment]
> Hi Guys,
> 
> I'm also receiving these messages:
> 0|camera | code: 'ER_BAD_DB_ERROR',
> 0|camera | errno: 1049,
> 0|camera | sqlMessage: 'Unknown database 'ccio'',
> 0|camera | sqlState: '42000',
> 0|camera | fatal: true }
> 
> I can't add a user after logging into /super
> When I hit save, nothing happens
> 
> I also can't change the [admin@shinobi.video](mailto:admin@shinobi.video) password, could this be SQL related?
> 
> Thanks.
--
Hey nate, Probably your database is not installed properly. Try passing the environment arguments. DB_USER=root DB_PASS=root DB_NAME=shinobi

**Comment by Ulisses1478** [comment]
and if you are not using unraid is good to see the readme file.

**Comment by nate922** [comment]
Ulisses1478, THANK YOU :)

Passing the database environment works!

Have a good day.

**Comment by CurlyFlow** [comment]
if anyone ever has this problem.. (and all unraid users must do this) add the env variables like descriped, BUT change DB_NAME to ccio, and it works.
